sonar.projectKey=DAII-tpo_DAII-Grupo-8-Frontend
sonar.organization=daii-tpo

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,src/test/**
sonar.exclusions=**/*.test.ts,**/*.test.tsx,src/test/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info