import { MantineProvider } from '@mantine/core';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { bikeService } from '../../services/bikes/bikeService';
import { stationService } from '../../services/stations/stationService';
import { mantineTheme } from '../../styles/theme';
import { BikeManagement } from './BikeManagement';

vi.mock('../../services/bikes/bikeService', () => ({ bikeService: { changeStatus: vi.fn(), create: vi.fn(), getByStation: vi.fn(), remove: vi.fn(), transfer: vi.fn() } }));
vi.mock('../../services/stations/stationService', () => ({ stationService: { getAll: vi.fn() } }));
const stations = [{ id: 2, name: 'Centro', address: '', latitude: 0, longitude: 0, capacity: 10, status: 'ACTIVE' as const, createdAt: '', updatedAt: '', deletedAt: null }, { id: 3, name: 'Norte', address: '', latitude: 0, longitude: 0, capacity: 10, status: 'ACTIVE' as const, createdAt: '', updatedAt: '', deletedAt: null }];
const bike = { id: 1, code: 'B-1', stationId: 2, stationName: 'Centro', status: 'AVAILABLE' as const, model: null, purchaseDate: null, lastMaintenanceAt: null, createdAt: '', updatedAt: '' };
function renderPage() { return render(<MantineProvider theme={mantineTheme}><BikeManagement /></MantineProvider>); }
function error(status: number, message?: string) { return Object.assign(new Error('x'), { isAxiosError: true, response: { status, data: message ? { message } : undefined } }); }
afterEach(() => { cleanup(); vi.resetAllMocks(); });
describe('BikeManagement', () => {
  it('carga estaciones, bicicletas por estación y filtra localmente', async () => { vi.mocked(stationService.getAll).mockResolvedValueOnce(stations); vi.mocked(bikeService.getByStation).mockResolvedValueOnce([bike, { ...bike, id: 2, code: 'B-2', status: 'MAINTENANCE' }]); renderPage(); fireEvent.change(await screen.findByLabelText('Estación para bicicletas'), { target: { value: '2' } }); expect(await screen.findByText('B-1')).toBeInTheDocument(); fireEvent.change(screen.getByLabelText('Filtro de estado'), { target: { value: 'MAINTENANCE' } }); expect(screen.queryByText('B-1')).not.toBeInTheDocument(); expect(screen.getByText('B-2')).toBeInTheDocument(); });
  it('crea, cambia estado y elimina después de confirmación', async () => { vi.mocked(stationService.getAll).mockResolvedValue(stations); vi.mocked(bikeService.getByStation).mockResolvedValue([bike]); vi.mocked(bikeService.create).mockResolvedValueOnce({ ...bike, id: 4, code: 'B-4' }); vi.mocked(bikeService.changeStatus).mockResolvedValueOnce({ ...bike, status: 'MAINTENANCE' }); vi.mocked(bikeService.remove).mockResolvedValueOnce(); renderPage(); fireEvent.change(await screen.findByLabelText('Estación para bicicletas'), { target: { value: '2' } }); await screen.findByText('B-1'); fireEvent.change(screen.getByLabelText('Código'), { target: { value: 'B-4' } }); fireEvent.click(screen.getByRole('button', { name: 'Crear bicicleta' })); expect(await screen.findByText('La bicicleta fue creada.')).toBeInTheDocument(); fireEvent.change(screen.getByLabelText('Cambiar estado B-1'), { target: { value: 'MAINTENANCE' } }); await waitFor(() => expect(bikeService.changeStatus).toHaveBeenCalledWith(1, { status: 'MAINTENANCE', reason: null })); await screen.findByText('El estado de la bicicleta fue actualizado.'); fireEvent.click(screen.getAllByRole('button', { name: 'Baja' })[0]); fireEvent.click(screen.getByRole('button', { name: 'Confirmar baja' })); await waitFor(() => expect(bikeService.remove).toHaveBeenCalledWith(1)); });
  it('traslada una bicicleta usando el selector de estaciones', async () => { vi.mocked(stationService.getAll).mockResolvedValue(stations); vi.mocked(bikeService.getByStation).mockResolvedValue([bike]); vi.mocked(bikeService.transfer).mockResolvedValue({ ...bike, stationId: 3 }); renderPage(); fireEvent.change(await screen.findByLabelText('Estación para bicicletas'), { target: { value: '2' } }); await screen.findByText('B-1'); fireEvent.change(screen.getByLabelText('Trasladar B-1'), { target: { value: '3' } }); await waitFor(() => expect(bikeService.transfer).toHaveBeenCalledWith(1, { stationId: 3 })); expect(await screen.findByText('La bicicleta fue trasladada.')).toBeInTheDocument(); });
  it('conserva la lista y muestra el mensaje de conflicto al fallar un cambio de estado', async () => { vi.mocked(stationService.getAll).mockResolvedValue(stations); vi.mocked(bikeService.getByStation).mockResolvedValue([bike]); vi.mocked(bikeService.changeStatus).mockRejectedValue(error(409, 'La bicicleta está en uso.')); renderPage(); fireEvent.change(await screen.findByLabelText('Estación para bicicletas'), { target: { value: '2' } }); await screen.findByText('B-1'); fireEvent.change(screen.getByLabelText('Cambiar estado B-1'), { target: { value: 'MAINTENANCE' } }); expect(await screen.findByText('La bicicleta está en uso.')).toBeInTheDocument(); expect(screen.getByText('B-1')).toBeInTheDocument(); });
});
