import { MantineProvider } from '@mantine/core';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { stationService } from '../../services/stations/stationService';
import { mantineTheme } from '../../styles/theme';
import { StationManagement } from './StationManagement';

vi.mock('../../services/stations/stationService', () => ({ stationService: { create: vi.fn(), getAll: vi.fn(), update: vi.fn() } }));
const station = { id: 2, name: 'Centro', address: 'Av. Siempre Viva', latitude: -34.6, longitude: -58.4, capacity: 20, status: 'ACTIVE' as const, createdAt: '', updatedAt: '', deletedAt: null };
function renderPage() { return render(<MantineProvider theme={mantineTheme}><StationManagement /></MantineProvider>); }
function error(status?: number) { return Object.assign(new Error('x'), { isAxiosError: true, response: { status } }); }
afterEach(() => { cleanup(); vi.resetAllMocks(); });
describe('StationManagement', () => {
  it('muestra loading y el listado real', async () => { vi.mocked(stationService.getAll).mockResolvedValueOnce([station]); renderPage(); expect(screen.getByText('Cargando estaciones...')).toBeInTheDocument(); expect(await screen.findByText('Centro')).toBeInTheDocument(); });
  it('muestra vacío, error y permite reintentar', async () => { vi.mocked(stationService.getAll).mockRejectedValueOnce(error()).mockResolvedValueOnce([]); renderPage(); expect(await screen.findByText('No se pudieron cargar las estaciones.')).toBeInTheDocument(); });
  it('crea una estación solo luego de la respuesta exitosa', async () => { vi.mocked(stationService.getAll).mockResolvedValueOnce([]); let resolve!: (s: typeof station) => void; vi.mocked(stationService.create).mockReturnValueOnce(new Promise((r) => { resolve = r; })); renderPage(); await screen.findByText('No hay estaciones registradas.'); fireEvent.change(screen.getByLabelText('Nombre'), { target: { value: 'Centro' } }); fireEvent.click(screen.getByRole('button', { name: 'Crear estación' })); expect(screen.queryByText('Centro')).not.toBeInTheDocument(); resolve(station); expect(await screen.findByText('La estación fue creada.')).toBeInTheDocument(); expect(stationService.create).toHaveBeenCalledWith({ name: 'Centro', address: null, latitude: -34.6, longitude: -58.4, capacity: 10, status: 'ACTIVE' }); });
  it('muestra el mensaje adecuado si el alta es rechazada por el backend', async () => { vi.mocked(stationService.getAll).mockResolvedValue([]); vi.mocked(stationService.create).mockRejectedValue(error(400)); renderPage(); await screen.findByText('No hay estaciones registradas.'); fireEvent.change(screen.getByLabelText('Nombre'), { target: { value: 'Centro' } }); fireEvent.click(screen.getByRole('button', { name: 'Crear estación' })); expect(await screen.findByText('Revisá los datos ingresados.')).toBeInTheDocument(); });
  it('edita y desactiva enviando el DTO completo', async () => { vi.mocked(stationService.getAll).mockResolvedValue([station]); vi.mocked(stationService.update).mockResolvedValueOnce({ ...station, name: 'Centro editado' }).mockResolvedValueOnce({ ...station, name: 'Centro editado', status: 'INACTIVE' }); renderPage(); await screen.findByText('Centro'); fireEvent.click(screen.getByRole('button', { name: 'Editar' })); expect(screen.getByLabelText('Nombre')).toHaveValue('Centro'); fireEvent.change(screen.getByLabelText('Nombre'), { target: { value: 'Centro editado' } }); fireEvent.click(screen.getByRole('button', { name: 'Guardar cambios' })); expect(await screen.findByText('La estación fue actualizada.')).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: 'Desactivar' })); fireEvent.click(screen.getAllByRole('button', { name: 'Desactivar' })[0]); await waitFor(() => expect(stationService.update).toHaveBeenCalledTimes(2)); expect(stationService.update).toHaveBeenLastCalledWith(2, { name: 'Centro editado', address: 'Av. Siempre Viva', latitude: -34.6, longitude: -58.4, capacity: 20, status: 'INACTIVE' }); });
});
