import { Alert, Button, Group, NativeSelect, NumberInput, Paper, Stack, Table, Text, TextInput, Title } from '@mantine/core';
import { isAxiosError } from 'axios';
import { useCallback, useEffect, useState } from 'react';

import { stationService } from '../../services/stations/stationService';
import type { Station, StationRequest, StationStatus } from '../../types/station';
import classes from './Administration.module.css';

const emptyForm: StationRequest = { name: '', address: null, latitude: -34.6, longitude: -58.4, capacity: 10, status: 'ACTIVE' };

export function StationManagement() {
  const [stations, setStations] = useState<Station[]>([]); const [form, setForm] = useState<StationRequest>(emptyForm); const [editing, setEditing] = useState<Station | null>(null); const [loading, setLoading] = useState(true); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null); const [confirm, setConfirm] = useState<Station | null>(null);
  const load = useCallback(async () => { setLoading(true); try { setStations(await stationService.getAll()); setError(null); } catch { setError('No se pudieron cargar las estaciones.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const save = async () => { if (!form.name.trim() || form.capacity <= 0) return; setPending(true); setError(null); try { const saved = editing ? await stationService.update(editing.id, form) : await stationService.create(form); setStations((items) => editing ? items.map((item) => item.id === saved.id ? saved : item) : [...items, saved]); setSuccess(editing ? 'La estación fue actualizada.' : 'La estación fue creada.'); setEditing(null); setForm(emptyForm); } catch (requestError) { setError(message(requestError)); } finally { setPending(false); } };
  const edit = (station: Station) => { setEditing(station); setForm({ name: station.name, address: station.address || null, latitude: station.latitude, longitude: station.longitude, capacity: station.capacity, status: station.status }); };
  const deactivate = async () => { if (!confirm) return; setPending(true); try { const updated = await stationService.update(confirm.id, { name: confirm.name, address: confirm.address || null, latitude: confirm.latitude, longitude: confirm.longitude, capacity: confirm.capacity, status: 'INACTIVE' }); setStations((items) => items.map((item) => item.id === updated.id ? updated : item)); setSuccess('La estación fue desactivada.'); setConfirm(null); } catch (requestError) { setError(message(requestError)); } finally { setPending(false); } };
  return <Stack gap="lg">{error ? <Alert color="red">{error}</Alert> : null}{success ? <Alert color="green">{success}</Alert> : null}<Paper className={classes.formPanel} p="md"><Stack><Title order={2} className={classes.sectionTitle}>{editing ? 'Editar estación' : 'Crear estación'}</Title><TextInput label="Nombre" value={form.name} onChange={(e) => setForm({ ...form, name: e.currentTarget.value })} maxLength={150} /><TextInput label="Dirección" value={form.address ?? ''} onChange={(e) => setForm({ ...form, address: e.currentTarget.value || null })} maxLength={255} /><Group grow><NumberInput label="Latitud" value={form.latitude} onChange={(value) => setForm({ ...form, latitude: Number(value) })} /><NumberInput label="Longitud" value={form.longitude} onChange={(value) => setForm({ ...form, longitude: Number(value) })} /><NumberInput label="Capacidad" min={1} max={1000} value={form.capacity} onChange={(value) => setForm({ ...form, capacity: Number(value) })} /></Group><NativeSelect label="Estado" value={form.status} onChange={(e) => setForm({ ...form, status: e.currentTarget.value as StationStatus })} data={[{ value: 'ACTIVE', label: 'Activa' }, { value: 'INACTIVE', label: 'Inactiva' }, { value: 'MAINTENANCE', label: 'Mantenimiento' }]} /><Group><Button loading={pending} onClick={() => void save()}>{editing ? 'Guardar cambios' : 'Crear estación'}</Button>{editing ? <Button variant="default" onClick={() => { setEditing(null); setForm(emptyForm); }}>Cancelar</Button> : null}</Group></Stack></Paper>{confirm ? <Alert color="orange" title="Confirmar desactivación"><Group justify="space-between"><Text>¿Desactivar {confirm.name}?</Text><Group><Button color="red" loading={pending} onClick={() => void deactivate()}>Desactivar</Button><Button variant="default" onClick={() => setConfirm(null)}>Cancelar</Button></Group></Group></Alert> : null}{loading ? <Text>Cargando estaciones...</Text> : stations.length === 0 ? <Text c="dimmed">No hay estaciones registradas.</Text> : <Paper className={classes.tablePanel} p="md"><Table><Table.Thead><Table.Tr><Table.Th>Nombre</Table.Th><Table.Th>Dirección</Table.Th><Table.Th>Capacidad</Table.Th><Table.Th>Estado</Table.Th><Table.Th /></Table.Tr></Table.Thead><Table.Tbody>{stations.map((station) => <Table.Tr key={station.id}><Table.Td>{station.name}</Table.Td><Table.Td>{station.address || 'Sin dirección'}</Table.Td><Table.Td>{station.capacity}</Table.Td><Table.Td>{station.status}</Table.Td><Table.Td><Group><Button size="compact-sm" variant="light" onClick={() => edit(station)}>Editar</Button>{station.status !== 'INACTIVE' ? <Button size="compact-sm" color="red" variant="light" onClick={() => setConfirm(station)}>Desactivar</Button> : null}</Group></Table.Td></Table.Tr>)}</Table.Tbody></Table></Paper>}</Stack>;
}
function message(error: unknown) { if (!isAxiosError(error)) return 'No se pudo completar la operación.'; if (error.response?.status === 400) return 'Revisá los datos ingresados.'; if (error.response?.status === 404) return 'El recurso solicitado ya no existe.'; return 'No se pudo completar la operación. Intentá nuevamente.'; }
